name: scan_check
on:
  pull_request:
    types: [opened]
  workflow_dispatch :
  push :
    branches:    
      - 'main'
jobs:
   scan_check:
       runs-on: ${{ matrix.os }}
       strategy:
         matrix:
           os: [ ubuntu-latest ]
       steps:
         - uses: actions/checkout@v2
         - run: chmod +x ./zscanner.sh
         - run: ./zscanner.sh
